export const countryList = [
  { key: "Select Your Country", value: "" },
  { value: "AFG", key: "Afghanistan" },
  { value: "ALB", key: "Albania" },
  { value: "DZA", key: "Algeria" },
  { value: "ASM", key: "American Samoa" },
  { value: "AND", key: "Andorra" },
  { value: "AGO", key: "Angola" },
  { value: "AIA", key: "Anguilla" },
  { value: "ATA", key: "Antarctica" },
  { value: "ATG", key: "Antigua and Barbuda" },
  { value: "ARG", key: "Argentina" },
  { value: "ARM", key: "Armenia" },
  { value: "ABW", key: "Aruba" },
  { value: "AUS", key: "Australia" },
  { value: "AUT", key: "Austria" },
  { value: "AZE", key: "Azerbaijan" },
  { value: "BHS", key: "Bahamas (the)" },
  { value: "BHR", key: "Bahrain" },
  { value: "BGD", key: "Bangladesh" },
  { value: "BRB", key: "Barbados" },
  { value: "BLR", key: "Belarus" },
  { value: "BEL", key: "Belgium" },
  { value: "BLZ", key: "Belize" },
  { value: "BEN", key: "Benin" },
  { value: "BMU", key: "Bermuda" },
  { value: "BTN", key: "Bhutan" },
  { value: "BOL", key: "Bolivia (Plurinational State of)" },
  { value: "BES", key: "Bonaire,}, Sint Eustatius and Saba" },
  { value: "BIH", key: "Bosnia and Herzegovina" },
  { value: "BWA", key: "Botswana" },
  { value: "BVT", key: "Bouvet Island" },
  { value: "BRA", key: "Brazil" },
  { value: "IOT", key: "British Indian Ocean Territory (the)" },
  { value: "BRN", key: "Brunei Darussalam" },
  { value: "BGR", key: "Bulgaria" },
  { value: "BFA", key: "Burkina Faso" },
  { value: "BDI", key: "Burundi" },
  { value: "CPV", key: "Cabo Verde" },
  { value: "KHM", key: "Cambodia" },
  { value: "CMR", key: "Cameroon" },
  { value: "CAN", key: "Canada" },
  { value: "CYM", key: "Cayman Islands (the)" },
  { value: "CAF", key: "Central African Republic (the)" },
  { value: "TCD", key: "Chad" },
  { value: "CHL", key: "Chile" },
  { value: "CHN", key: "China" },
  { value: "CXR", key: "Christmas Island" },
  { value: "CCK", key: "Cocos (Keeling) Islands (the)" },
  { value: "COL", key: "Colombia" },
  { value: "COM", key: "Comoros (the)" },
  { value: "COD", key: "Congo (the Democratic Republic of the)" },
  { value: "COG", key: "Congo (the)" },
  { value: "COK", key: "Cook Islands (the)" },
  { value: "CRI", key: "Costa Rica" },
  { value: "HRV", key: "Croatia" },
  { value: "CUB", key: "Cuba" },
  { value: "CUW", key: "Curaçao" },
  { value: "CYP", key: "Cyprus" },
  { value: "CZE", key: "Czechia" },
  { value: "CIV", key: "Côte d'Ivoire" },
  { value: "DNK", key: "Denmark" },
  { value: "DJI", key: "Djibouti" },
  { value: "DMA", key: "Dominica" },
  { value: "DOM", key: "Dominican Republic (the)" },
  { value: "ECU", key: "Ecuador" },
  { value: "EGY", key: "Egypt" },
  { value: "SLV", key: "El Salvador" },
  { value: "GNQ", key: "Equatorial Guinea" },
  { value: "ERI", key: "Eritrea" },
  { value: "EST", key: "Estonia" },
  { value: "SWZ", key: "Eswatini" },
  { value: "ETH", key: "Ethiopia" },
  { value: "FLK", key: "Falkland Islands (the) [Malvinas]" },
  { value: "FRO", key: "Faroe Islands (the)" },
  { value: "FJI", key: "Fiji" },
  { value: "FIN", key: "Finland" },
  { value: "FRA", key: "France" },
  { value: "GUF", key: "French Guiana" },
  { value: "PYF", key: "French Polynesia" },
  { value: "ATF", key: "French Southern Territories (the)" },
  { value: "GAB", key: "Gabon" },
  { value: "GMB", key: "Gambia (the)" },
  { value: "GEO", key: "Georgia" },
  { value: "DEU", key: "Germany" },
  { value: "GHA", key: "Ghana" },
  { value: "GIB", key: "Gibraltar" },
  { value: "GRC", key: "Greece" },
  { value: "GRL", key: "Greenland" },
  { value: "GRD", key: "Grenada" },
  { value: "GLP", key: "Guadeloupe" },
  { value: "GUM", key: "Guam" },
  { value: "GTM", key: "Guatemala" },
  { value: "GGY", key: "Guernsey" },
  { value: "GIN", key: "Guinea" },
  { value: "GNB", key: "Guinea-Bissau" },
  { value: "GUY", key: "Guyana" },
  { value: "HTI", key: "Haiti" },
  { value: "HMD", key: "Heard Island and McDonald Islands" },
  { value: "VAT", key: "Holy See (the)" },
  { value: "HND", key: "Honduras" },
  { value: "HKG", key: "Hong Kong" },
  { value: "HUN", key: "Hungary" },
  { value: "ISL", key: "Iceland" },
  { value: "IND", key: "India" },
  { value: "IDN", key: "Indonesia" },
  { value: "IRN", key: "Iran (Islamic Republic of)" },
  { value: "IRQ", key: "Iraq" },
  { value: "IRL", key: "Ireland" },
  { value: "IMN", key: "Isle of Man" },
  { value: "ISR", key: "Israel" },
  { value: "ITA", key: "Italy" },
  { value: "JAM", key: "Jamaica" },
  { value: "JPN", key: "Japan" },
  { value: "JEY", key: "Jersey" },
  { value: "JOR", key: "Jordan" },
  { value: "KAZ", key: "Kazakhstan" },
  { value: "KEN", key: "Kenya" },
  { value: "KIR", key: "Kiribati" },
  { value: "PRK", key: "Korea (the Democratic People's Republic of)" },
  { value: "KOR", key: "Korea (the Republic of)" },
  { value: "KWT", key: "Kuwait" },
  { value: "KGZ", key: "Kyrgyzstan" },
  { value: "LAO", key: "Lao People's Democratic Republic (the)" },
  { value: "LVA", key: "Latvia" },
  { value: "LBN", key: "Lebanon" },
  { value: "LSO", key: "Lesotho" },
  { value: "LBR", key: "Liberia" },
  { value: "LBY", key: "Libya" },
  { value: "LIE", key: "Liechtenstein" },
  { value: "LTU", key: "Lithuania" },
  { value: "LUX", key: "Luxembourg" },
  { value: "MAC", key: "Macao" },
  { value: "MDG", key: "Madagascar" },
  { value: "MWI", key: "Malawi" },
  { value: "MYS", key: "Malaysia" },
  { value: "MDV", key: "Maldives" },
  { value: "MLI", key: "Mali" },
  { value: "MLT", key: "Malta" },
  { value: "MHL", key: "Marshall Islands (the)" },
  { value: "MTQ", key: "Martinique" },
  { value: "MRT", key: "Mauritania" },
  { value: "MUS", key: "Mauritius" },
  { value: "MYT", key: "Mayotte" },
  { value: "MEX", key: "Mexico" },
  { value: "FSM", key: "Micronesia (Federated States of)" },
  { value: "MDA", key: "Moldova (the Republic of)" },
  { value: "MCO", key: "Monaco" },
  { value: "MNG", key: "Mongolia" },
  { value: "MNE", key: "Montenegro" },
  { value: "MSR", key: "Montserrat" },
  { value: "MAR", key: "Morocco" },
  { value: "MOZ", key: "Mozambique" },
  { value: "MMR", key: "Myanmar" },
  { value: "NAM", key: "Namibia" },
  { value: "NRU", key: "Nauru" },
  { value: "NPL", key: "Nepal" },
  { value: "NLD", key: "Netherlands (the)" },
  { value: "NCL", key: "New Caledonia" },
  { value: "NZL", key: "New Zealand" },
  { value: "NIC", key: "Nicaragua" },
  { value: "NER", key: "Niger (the)" },
  { value: "NGA", key: "Nigeria" },
  { value: "NIU", key: "Niue" },
  { value: "NFK", key: "Norfolk Island" },
  { value: "MNP", key: "Northern Mariana Islands (the)" },
  { value: "NOR", key: "Norway" },
  { value: "OMN", key: "Oman" },
  { value: "PAK", key: "Pakistan" },
  { value: "PLW", key: "Palau" },
  { value: "PSE", key: "Palestine,}, State of" },
  { value: "PAN", key: "Panama" },
  { value: "PNG", key: "Papua New Guinea" },
  { value: "PRY", key: "Paraguay" },
  { value: "PER", key: "Peru" },
  { value: "PHL", key: "Philippines (the)" },
  { value: "PCN", key: "Pitcairn" },
  { value: "POL", key: "Poland" },
  { value: "PRT", key: "Portugal" },
  { value: "PRI", key: "Puerto Rico" },
  { value: "QAT", key: "Qatar" },
  { value: "MKD", key: "Republic of North Macedonia" },
  { value: "ROU", key: "Romania" },
  { value: "RUS", key: "Russian Federation (the)" },
  { value: "RWA", key: "Rwanda" },
  { value: "REU", key: "Réunion" },
  { value: "BLM", key: "Saint Barthélemy" },
  { value: "SHN", key: "Saint Helena,}, Ascension and Tristan da Cunha" },
  { value: "KNA", key: "Saint Kitts and Nevis" },
  { value: "LCA", key: "Saint Lucia" },
  { value: "MAF", key: "Saint Martin (French part)" },
  { value: "SPM", key: "Saint Pierre and Miquelon" },
  { value: "VCT", key: "Saint Vincent and the Grenadines" },
  { value: "WSM", key: "Samoa" },
  { value: "SMR", key: "San Marino" },
  { value: "STP", key: "Sao Tome and Principe" },
  { value: "SAU", key: "Saudi Arabia" },
  { value: "SEN", key: "Senegal" },
  { value: "SRB", key: "Serbia" },
  { value: "SYC", key: "Seychelles" },
  { value: "SLE", key: "Sierra Leone" },
  { value: "SGP", key: "Singapore" },
  { value: "SXM", key: "Sint Maarten (Dutch part)" },
  { value: "SVK", key: "Slovakia" },
  { value: "SVN", key: "Slovenia" },
  { value: "SLB", key: "Solomon Islands" },
  { value: "SOM", key: "Somalia" },
  { value: "ZAF", key: "South Africa" },
  { value: "SGS", key: "South Georgia and the South Sandwich Islands" },
  { value: "SSD", key: "South Sudan" },
  { value: "ESP", key: "Spain" },
  { value: "LKA", key: "Sri Lanka" },
  { value: "SDN", key: "Sudan (the)" },
  { value: "SUR", key: "Suriname" },
  { value: "SJM", key: "Svalbard and Jan Mayen" },
  { value: "SWE", key: "Sweden" },
  { value: "CHE", key: "Switzerland" },
  { value: "SYR", key: "Syrian Arab Republic" },
  { value: "TWN", key: "Taiwan" },
  { value: "TJK", key: "Tajikistan" },
  { value: "TZA", key: "Tanzania,}, United Republic of" },
  { value: "THA", key: "Thailand" },
  { value: "TLS", key: "Timor-Leste" },
  { value: "TGO", key: "Togo" },
  { value: "TKL", key: "Tokelau" },
  { value: "TON", key: "Tonga" },
  { value: "TTO", key: "Trinidad and Tobago" },
  { value: "TUN", key: "Tunisia" },
  { value: "TUR", key: "Turkey" },
  { value: "TKM", key: "Turkmenistan" },
  { value: "TCA", key: "Turks and Caicos Islands (the)" },
  { value: "TUV", key: "Tuvalu" },
  { value: "UGA", key: "Uganda" },
  { value: "UKR", key: "Ukraine" },
  { value: "ARE", key: "United Arab Emirates (the)" },
  {
    value: "GBR",
    key: "United Kingdom of Great Britain and Northern Ireland (the)",
  },
  { value: "UMI", key: "United States Minor Outlying Islands (the)" },
  { value: "USA", key: "United States of America (the)" },
  { value: "URY", key: "Uruguay" },
  { value: "UZB", key: "Uzbekistan" },
  { value: "VUT", key: "Vanuatu" },
  { value: "VEN", key: "Venezuela (Bolivarian Republic of)" },
  { value: "VNM", key: "Viet Nam" },
  { value: "VGB", key: "Virgin Islands (British)" },
  { value: "VIR", key: "Virgin Islands (U.S.)" },
  { value: "WLF", key: "Wallis and Futuna" },
  { value: "ESH", key: "Western Sahara" },
  { value: "YEM", key: "Yemen" },
  { value: "ZMB", key: "Zambia" },
  { value: "ZWE", key: "Zimbabwe" },
  { value: "ALA", key: "Åland Islands" },
];
